### ISSUE TITLE
Calculate stats for dataset

### ISSUE THREAD

**Issue by 4-en** [4-en/LoL-Win-Prediction#2]
Create functions to calculate some stats that can be used to measure model performance.

Eg.: champion wr, champion wr vs other champions, best winrates, pickrate, positions (not sure if its in the dataset)
Test models against predictable matches, eg all high wr vs all low wr, champs vs their counters

**Comment by otsoweckstrom** [comment]
Check individual champion winrates, compare each champions average winrate to the winrate when playing against each champion to find counters
